#!/bin/bash

CONFIG_SRC_DIR=~/Documents/configuration/src
POWERLINE_BINDINGS="/home/linuxbrew/.linuxbrew/lib/python3.6/site-packages/powerline/bindings/tmux/powerline.conf"

brew install tmux

if [ ! -d $CONFIG_SRC_DIR/.tmux ]; then
    git clone https://github.com/CaptainQuirk/.tmux.git $CONFIG_SRC_DIR/.tmux
    cd $CONFIG_SRC_DIR/.tmux
    git submodule update --init --recursive
    cd -
fi

if [ ! -L ~/.tmux.conf ]; then
    ln -s -f $CONFIG_SRC_DIR/.tmux/tmux.conf ~/.tmux.conf
fi

if [ ! -f $HOME/.tmux-plugins.conf ]; then
    echo "run-shell '$CONFIG_SRC_DIR/.tmux/plugins/tpm/tpm'" > ~/.tmux-plugins.conf
fi

if [ ! -f $HOME/.tmux-powerline.conf ]; then
   echo "POWERLINE_PATH=$POWERLINE_BINDINGS" > ~/.tmux-powerline.conf
   chmod +x $POWERLINE_BINDINGS
fi

brew install urlview
