#!/bin/bash

shef brew ruby
shef brew tmux

shef git "Download tmux configuration" \
    --repository https://github.com/CaptainQuirk/.tmux.git \
    --destination "$CONFIG_SRC_DIR/.tmux" \
    --enable-submodules

shef link "Symlink global tmux.conf" \
    --target "$CONFIG_SRC_DIR/.tmux/tmux.conf" \
    --to "$HOME/.tmux.conf" \
    --force

shef apt urlview


gem install tmuxinator
